### ISSUE TITLE
Error loading mesh on tile-3d 

### ISSUE THREAD

**Issue by quannh997** [visgl/loaders.gl#2018]
Hi!

I have tried load **Tile3DLayer** with both type loader I3SLoader, Tiles3dLoader for my region but they have same issue is tile have crack like earthquake and quality mesh is so bad. I think maybe reason is my server but when i tried data i3s on arcgis server, arcgis scene is showing data is good, but i loaded this scene on loader code example the issues still happend. 
ArcGis Scene:
![image](https://user-images.githubusercontent.com/61110829/146187948-a688cc84-3293-41a4-9ae4-77bb019c524a.png)
In code example
![image](https://user-images.githubusercontent.com/61110829/146188250-b251dc10-0323-4db1-9ff7-d358991a59e3.png)

The data i use here: "https://tiles.arcgis.com/tiles/6isf2oKhmeNEAK04/arcgis/rest/services/TextureMesh_v17/SceneServer/layers/0"

Can explain for me how and why i can handle that thing?

**Comment by belom88** [comment]
Looks like precision issue we fixed recently. You need do use `LNGLAT_OFFSETS` coordinate system like here in example:
https://github.com/visgl/loaders.gl/blob/5bf1db80e532cde86b92dcbaee50696632e94d7b/examples/website/i3s/app.js#L241

**Comment by quannh97** [comment]
> Looks like precision issue we fixed recently. You need do use `LNGLAT_OFFSETS` coordinate system like here in example:
> 
> https://github.com/visgl/loaders.gl/blob/5bf1db80e532cde86b92dcbaee50696632e94d7b/examples/website/i3s/app.js#L241

it not work for me, the problem is when i use LNGLAT_OFFSETS, tiles doesn't shown up. But coordinateSystem is METER_OFFSETS or IDENTITY, i3s show normaly but the errors still theres, nothing change.

**Comment by belom88** [comment]
I need to check. I need token for your layer example

**Comment by quannh97** [comment]
> I need to check. I need token for your layer example

Solve the problem when upgrade @loaders.gl to alpha 4.5 and deck.gl to 8.7.0-alpha 11. 
I have another question,
I try to test data on type i3s and b3dm, the tile-3d-loader can clear tile loaded in memory, so memory used is between 1-2 gb max. but with i3s-loader, tile loaded in memory is stack-up, can't clear tile in out of the current view. Memory ascending to 3 gb. 
The problem is I want to use i3s type cause it convenient to process, the data is on local server, so if you want the data to test, I can provide. 
How can I clear the data saved in memory  and keep only tile loading in view for the performance.
Did it involve with compareDistanceToCamera and updateTileVisibility in Tileset3DTraverser.

Thanks!
![image](https://user-images.githubusercontent.com/87181330/150176237-0929b623-d528-4619-9f25-ff70805f0daf.png)

**Comment by ibgreen** [comment]
loaders.gl 4.0.0-alpha is a breaking, currently very unstable branch that lacks a number of fixes from 3.1 track. I strongly recommend against using it.

**Comment by quannh997** [comment]
> loaders.gl 4.0.0-alpha is a breaking, currently very unstable branch that lacks a number of fixes from 3.1 track. I strongly recommend against using it.

Thanks for advice, i change to 3.1.6 statble, but still jave another question for memory, any way to clear tile cache for i3sloader? For now or feature update.

**Comment by belom88** [comment]
We need your data set to check it there are memory leaks

**Comment by quannh97** [comment]
> We need your data set to check it there are memory leaks

The data link is : [https://drive.google.com/drive/folders/1ycERC-UUkBM9wSVLKK4jwiXv21_bZRGJ](url)

I test with i3s 1.7 loaders.gl 3.1.7 with base map on harp.gl

**Comment by ibgreen** [comment]
Closing the original rendering report as resolved: the reporter confirmed that upgrading loaders.gl/deck.gl fixed that symptom. The later cache/memory question is a separate concern and would need a fresh issue with a current-version reproduction and dataset if it still occurs.
